apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rgcnyal6c-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rgcnyal6c-python 
  name: rgcnyal6c-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rgcnyal6c-python 
